import { Routes } from '@angular/router';
import { LandingComponent } from './components/landing/landing.component';
import { LoginComponent } from './components/login/login.component';
import { RegisterComponent } from './components/register/register.component';
import { DashboardComponent } from './components/dashboard/dashboard.component';
import { ParentalDashboardComponent } from './components/parental-dashboard/parental-dashboard.component';
import { AdminDashboardComponent } from './components/admin-dashboard/admin-dashboard.component';
import { RewardsComponent } from './components/rewards/rewards.component';
import { SubscriptionComponent } from './components/subscription/subscription.component';
import { ConfirmEmailComponent } from './components/confirm-email/confirm-email.component';
import { EmailVerifiedComponent } from './components/email-verified/email-verified.component';
import { ForgotPasswordComponent } from './components/forgot-password/forgot-password.component';
import { ResetPasswordComponent } from './components/reset-password/reset-password.component';
import { QuizComponent } from './components/quiz/quiz.component';
import { PuzzleComponent } from './components/puzzle/puzzle.component';
import { PdfViewerComponent } from './components/pdf-viewer/pdf-viewer.component';

export const routes: Routes = [
    { path: '', component: LandingComponent },
    { path: 'login', component: LoginComponent },
    { path: 'register', component: RegisterComponent },
    { path: 'dashboard', component: DashboardComponent },
    { path: 'parental-dashboard', component: ParentalDashboardComponent },
    { path: 'admin-dashboard', component: AdminDashboardComponent },
    { path: 'rewards', component: RewardsComponent },
    { path: 'subscription', component: SubscriptionComponent },
    { path: 'confirm-email', component: ConfirmEmailComponent },
    { path: 'verify-email', component: EmailVerifiedComponent },
    { path: 'forgot-password', component: ForgotPasswordComponent },
    { path: 'reset-password', component: ResetPasswordComponent },
    { path: 'quiz/:id', component: QuizComponent },
    { path: 'puzzle/:id', component: PuzzleComponent },
    { path: 'pdf-viewer', component: PdfViewerComponent }
];
