name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'stacktots-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        cd stacktots-backend
        npm install

    - name: Run tests
      run: |
        cd stacktots-backend
        npm test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./stacktots-backend
        file: ./stacktots-backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/stacktots-backend:latest
